### ISSUE TITLE
時間単位の不具合

### ISSUE THREAD

**Issue by omoidegit** [mmorise/multimodal-label#2]
こんにちは。

ずんだもんのEmoAma020~054のラベルデータの時間単位が、
他の「10^-7 s」ではなく、「s」になっているようです。

こちら、ご確認いただけると幸いです。

**Comment by mmorise** [comment]
ご指摘ありがとうございます．
先ほど修正したもので更新しました．

**Comment by omoidegit** [comment]
素早いご対応ありがとうございます。
